export const products = [
    {
      id: 1,
      title: "Samsung S21",
      description: "black in color",
      price: "2500",
      img: "pic1.jpg",
      quantity: 1,
    },
    {
      id: 2,
      title: "Samsung M21",
      description: "white in color",
      price: "2300",
      img: "pic1.jpg",
      quantity: 1,
    },
    {
      id: 3,
      title: "Redmi 9",
      description: "black in color",
      price: "3500",
      img: "pic1.jpg",
      quantity: 1,
    },
    {
      id: 4,
      title: "Iphone 12",
      description: "Best mobile ever",
      price: "90500",
      img: "pic1.jpg",
      quantity: 1,
    },
    {
      id: 5,
      title: "Samsung S21",
      description: "black in color",
      price: "2500",
      img: "pic1.jpg",
      quantity: 1,
    },
    {
      id: 6,
      title: "Redmi 9",
      description: "black in color",
      price: "3500",
      img: "pic1.jpg",
      quantity: 1,
    },
    {
      id: 7,
      title: "Samsung S21",
      description: "black in color",
      price: "2500",
      img: "pic1.jpg",
      quantity: 1,
    },
    {
      id: 8,
      title: "Iphone 12",
      description: "Best mobile ever",
      price: "90500",
      img: "pic1.jpg",
      quantity: 1,
    },
    {
      id: 9,
      title: "Samsung S21",
      description: "black in color",
      price: "2500",
      img: "pic1.jpg",
      quantity: 1,
    },
  ];